### ISSUE TITLE
怎么一直提示登录消息服务器失败

### ISSUE THREAD

**Issue by gaodeying** [vonway/teamtalk-ios#1]
我已经开了服务器，服务器是正常的。
运行蘑菇街里边那个没有适配iOS10的项目可以正常登录。
改了您的项目等ip结果不能登录，一直提示登录消息服务器失败，是什么原因那，还需要设置哪里吗

**Comment by vonway** [comment]
你的ip是在什么位置改的？
你可以在登陆界面的鹦鹉图标的上方空白处点击，
会出来一个服务器的地址，修改哪里的地址为你的服务器地址应该就可以了
